name: Label Check

on:
  pull_request:
    types: [opened, edited, labeled, unlabeled]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR has labels
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = context.payload.pull_request.labels;
            if (labels.length === 0) {
              core.setFailed('Please add at least one label to your pull request.');
            } else {
              labels.forEach(label => {
                console.log(`Label "${label.name}" is present in the pull request. `);
              });
            }
